### ISSUE TITLE
No such file 'coco-label.txt'

### ISSUE THREAD

**Issue by friskit-china** [James-Yip/AttentionImageClass#1]
Hi there,

Thanks you for your reproduction of the paper.

But when I ran this code, I got 'No such file or directory: coco-label.txt'

Did you forget to commit this file?

**Comment by James-Yip** [comment]
Sorry for the mistake.
I have committed this file now.

**Comment by friskit-china** [comment]
Thanks a lot! :)

**Comment by gittigxuy** [comment]
@friskit-china 
have you trained coco and voc dataset?could you pealse share your experience?
